
val main = fun() => {
	this.foo(try {} catch (e) {e});
}